### ISSUE TITLE
Strings?

### ISSUE THREAD

**Issue by revo23** [dwmetz/Mal-Hash#1]
strings : The term 'strings' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At C:\Users\xxx\xxx\xxx\xxx\mal-hash.ps1:49 char:1
+ strings -n 8 $script:file
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (strings:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

may i know how to deal with this error? thank you

**Comment by dwmetz** [comment]
It appears the system you're on does not have strings installed. For Windows: https://learn.microsoft.com/en-us/sysinternals/downloads/strings 
You'll want to ensure that whatever folder you have strings in is in your environment PATH.
